TRAIN:
  EPOCHS: 40
  SAVE_FRE: 10
  
  DIC_EPOCHS: 20
  DnCNN_EPOCHS: 20

  ICDM_EPOCHS: 50
  ICDM_SAVE_FRE: 1
  ICDM_TEST_FRE: 1

  TRAIN_PRINT_FRE: 1000

DATA:
  
  TRAIN_BATCH: 20
  TRAIN_ICDM_BATCH: 20
  TEST_BATCH: 1
  IMG_SIZE: 128

MODEL:
  LAMBDA: 1.0
  BETA : 1.0




