TRAIN:
  EPOCHS: 800
  SAVE_FRE: 100

  ICDM_EPOCHS: 1200
  ICDM_SAVE_FRE: 400
  ICDM_TEST_FRE: 1

  TRAIN_PRINT_FRE: 50
  
DATA:
  
  TRAIN_BATCH: 4
  TRAIN_ICDM_BATCH: 12
  TEST_BATCH: 1
  IMG_SIZE: 256


MODEL:
  LAMBDA: 1.5
  BETA : 1.0


