TRAIN:
  EPOCHS: 150
  SAVE_FRE: 10

  ICDM_EPOCHS: 2000
  ICDM_SAVE_FRE: 50
  ICDM_TEST_FRE: 10

  TRAIN_PRINT_FRE: 1000

DATA:
  
  TRAIN_BATCH: 20
  TRAIN_ICDM_BATCH: 20
  TEST_BATCH: 1
  IMG_SIZE: 128

MODEL:
  LAMBDA: 1.0
  BETA : 1.0




